### PR TITLE
Implement SCSS version

### PR DESCRIPTION
**Pull request by ghost**
Move less files into own folder (src/less)
Implement the same functionality based on SCSS.
Update README.md

### CODE REVIEW

**Comment by ghost** [comment]
Related issue: #4

**Comment by asika32764** [comment]
Thanks for your PR. I'll do some test and release a new minor version. 👍

**Comment by ghost** [comment]
@asika32764, any updates here? I would like to use that implementation in my project :)

**Comment by asika32764** [comment]
Released 2.0.0, please try it.

**Comment by ghost** [comment]
@asika32764, thanks for your fast response! :+1:
It works with the installation of `asika32764/vue2-animate#2.0.0`.

**Comment by ghost** [comment]
yes, it works fine. Thanks!

**Pull request merged**
